local BattleState = require("src.battle.BattleState")

-- National Dex registers modern moves with their real move data, but those
-- added moves do not have Gen 1 battle-animation programs. Reuse an existing
-- Gen 1 animation based on the move type instead of leaving them animationless.
local TYPE_ANIMS = {
  NORMAL = "TACKLE", FIRE = "EMBER", WATER = "WATER_GUN",
  ELECTRIC = "THUNDER_SHOCK", GRASS = "RAZOR_LEAF", ICE = "ICE_BEAM",
  FIGHTING = "LOW_KICK", POISON = "POISON_STING", GROUND = "SAND_ATTACK",
  FLYING = "GUST", PSYCHIC = "CONFUSION", BUG = "STRING_SHOT",
  ROCK = "ROCK_THROW", GHOST = "LICK", DRAGON = "DRAGON_RAGE",
  DARK = "LICK", STEEL = "ROCK_THROW", FAIRY = "CONFUSION"
}

-- Prefer the closest existing Gen 1 visual family over a simple type match.
-- Native Gen 1 animations are never replaced; this table only matters for
-- National Dex moves that have no native animation program.
local MOVE_ANIMS = {
  -- Normal: slashes, impacts, punches, kicks, bites
  SCRATCH="SCRATCH", SLASH="SLASH", FURYSWIPES="FURY_SWIPES",
  FALSESWIPE="SLASH", FURYCUTTER="SLASH", NIGHTSLA="SLASH",
  POUND="POUND", MEGAPUNCH="MEGA_PUNCH", DIZZYPUNCH="DIZZY_PUNCH",
  COMETPUNCH="COMET_PUNCH", MACH_PUNCH="MEGA_PUNCH", DRAINPUNCH="MEGA_PUNCH",
  DYNAMICPUNCH="MEGA_PUNCH", FOCUSPUNCH="MEGA_PUNCH",
  POWERUPPUNCH="MEGA_PUNCH", BULLETPUNCH="MEGA_PUNCH", HAMMERARM="MEGA_PUNCH",
  MEGAKICK="MEGA_KICK", JUMPKICK="JUMP_KICK", HIGHJUMPKICK="JUMP_KICK",
  LOWKICK="LOW_KICK", DOUBLEKICK="DOUBLE_KICK", TRIPLEKICK="DOUBLE_KICK",
  ROLLINGKICK="ROLLING_KICK", DOUBLEHIT="DOUBLE_KICK",
  TACKLE="TACKLE", BODYSLAM="BODY_SLAM", TAKEDOWN="TAKE_DOWN",
  DOUBLEEDGE="DOUBLE_EDGE", SLAM="SLAM", STOMP="STOMP",
  HEADBUTT="HEADBUTT", HEADCHARGE="HEADBUTT", SKULLBASH="SKULL_BASH",
  STRENGTH="STRENGTH", ROCKCLIMB="STRENGTH", RETALIATE="TACKLE",
  RETURN="TACKLE", FRUSTRATION="TACKLE", LASTRESORT="TACKLE",
  FACADE="TACKLE", SECRETPOWER="TACKLE", ENDEAVOR="TACKLE",
  EXTREMESPEED="QUICK_ATTACK", QUICKATTACK="QUICK_ATTACK",
  FAKEOUT="TACKLE", FEINT="SCRATCH",
  BITE="BITE", HYPERFANG="HYPER_FANG", CRUNCH="BITE",
  FIREFANG="FIRE_PUNCH", ICEFANG="ICE_PUNCH", THUNDERFANG="THUNDER_PUNCH",
  PSYCHICFANGS="BITE", JAWLOCK="BITE",
  PAYDAY="PAY_DAY", SWIFT="SWIFT", TRIATTACK="TRI_ATTACK",
  HYPERBEAM="HYPER_BEAM", GIGAIMPACT="HYPER_BEAM",
  BOOMBURST="HYPER_BEAM", HYPERVOICE="HYPER_BEAM",
  ROUND="HYPER_BEAM", ECHOEDVOICE="SONIC_BOOM", SONICBOOM="SONIC_BOOM",
  UPROAR="SONIC_BOOM", SNORE="SONIC_BOOM",
  SELFDESTRUCT="SELFDESTRUCT", EXPLOSION="EXPLOSION",
  EGGBOMB="EGG_BOMB", BARRAGE="BARRAGE", PRESENT="EGG_BOMB",
  WRAP="WRAP", BIND="BIND", CONSTRICT="CONSTRICT", CLAMP="CLAMP",
  INFESTATION="STRING_SHOT",

  -- Normal status / utility
  GROWL="GROWL", ROAR="ROAR", SCREECH="SCREECH", SING="SING",
  SUPERSONIC="SUPERSONIC", DISABLE="DISABLE", GLARE="GLARE",
  TAILWHIP="TAIL_WHIP", LEER="LEER", AGILITY="AGILITY",
  DOUBLETEAM="DOUBLE_TEAM", MINIMIZE="MINIMIZE", PROTECT="BARRIER",
  DETECT="BARRIER", ENDURE="BIDE", RECOVER="RECOVER", REST="REST",
  WISH="RECOVER", HEALBELL="SING", WORKUP="GROWTH", HOWL="GROWL",
  NASTYPLOT="GROWTH", CALMMIND="MEDITATE", BULKUP="MEDITATE",
  BELLYDRUM="MEDITATE", FOCUSENERGY="FOCUS_ENERGY", BATONPASS="AGILITY",
  SUBSTITUTE="SUBSTITUTE", METRONOME="METRONOME", MIMIC="MIMIC",
  CONVERSION="CONVERSION", CONVERSION2="CONVERSION", TRANSFORM="TRANSFORM",
  SPLASH="SPLASH",

  -- Fire
  FLAMECHARGE="EMBER", FLAMEWHEEL="FIRE_SPIN", FLAMETHROWER="FLAMETHROWER",
  FIREBLAST="FIRE_BLAST", FIRESPIN="FIRE_SPIN", HEATWAVE="FLAMETHROWER",
  LAVAPLUME="FIRE_SPIN", INFERNO="FIRE_SPIN", FIREPLEDGE="FIRE_SPIN",
  BLAZEKICK="FIRE_PUNCH", SACREDFIRE="FIRE_BLAST", BLUEFLARE="FIRE_BLAST",
  MYSTICALFIRE="FLAMETHROWER", OVERHEAT="FIRE_BLAST",
  FIERYDANCE="FIRE_SPIN", SEARINGSHOT="FIRE_BLAST", BURNUP="FIRE_BLAST",
  VCREATE="FIRE_BLAST",

  -- Water
  AQUAJET="WATER_GUN", AQUATAIL="WATER_GUN", WATERPULSE="WATER_GUN",
  AQUARING="WATER_GUN", HYDROPUMP="HYDRO_PUMP", SURF="SURF",
  WATERFALL="WATERFALL", BUBBLE="BUBBLE", BUBBLEBEAM="BUBBLEBEAM",
  SCALD="WATER_GUN", BRINE="WATER_GUN", MUDDYWATER="SURF",
  WHIRLPOOL="SURF", ORIGINPULSE="HYDRO_PUMP", LIQUIDATION="WATERFALL",
  RAZORSHELL="WATER_GUN", AQUACUTTER="WATER_GUN",

  -- Electric
  THUNDERSHOCK="THUNDER_SHOCK", THUNDERBOLT="THUNDERBOLT",
  THUNDERWAVE="THUNDER_WAVE", THUNDER="THUNDER", SPARK="THUNDER_SHOCK",
  ELECTROBALL="THUNDERBOLT", VOLTSWITCH="THUNDERBOLT",
  DISCHARGE="THUNDERBOLT", WILDCHARGE="THUNDERBOLT", ZAPCANNON="THUNDER",
  PARABOLICCHARGE="THUNDER_SHOCK", RISINGVOLTAGE="THUNDERBOLT",
  CHARGEBEAM="THUNDERBOLT", ELECTROWEB="THUNDER_WAVE",

  -- Grass
  ABSORB="ABSORB", MEGADRAIN="MEGA_DRAIN", GIGADRAIN="MEGA_DRAIN",
  DRAININGKISS="MEGA_DRAIN", HORNLEECH="VINE_WHIP", LEECHSEED="LEECH_SEED",
  GROWTH="GROWTH", RAZORLEAF="RAZOR_LEAF", LEAFBLADE="RAZOR_LEAF",
  VINEWHIP="VINE_WHIP", POWERWHIP="VINE_WHIP", SOLARBEAM="SOLARBEAM",
  ENERGYBALL="SOLARBEAM", SEEDBOMB="RAZOR_LEAF", BULLETSEED="RAZOR_LEAF",
  PETALDANCE="PETAL_DANCE", LEAFSTORM="SOLARBEAM", GRASSKNOT="VINE_WHIP",
  WOODHAMMER="VINE_WHIP", APPLEACID="RAZOR_LEAF", SEEDFLARE="SOLARBEAM",

  -- Ice
  ICEBEAM="ICE_BEAM", BLIZZARD="BLIZZARD", ICESHARD="ICE_BEAM",
  ICICLECRASH="ICE_BEAM", ICICLESPEAR="ICE_BEAM", FROSTBREATH="ICE_BEAM",
  AURORABEAM="AURORA_BEAM", FREEZEDRY="ICE_BEAM", ICESPINNER="ICE_BEAM",
  TRIPLEAXEL="ICE_PUNCH", MIST="MIST",

  -- Poison
  POISONSTING="POISON_STING", ACID="ACID", SLUDGE="SLUDGE",
  SLUDGEBOMB="SLUDGE", SLUDGEWAVE="SLUDGE", POISONGAS="POISON_GAS",
  SMOG="SMOG", TOXIC="TOXIC", VENOSHOCK="SLUDGE",
  ACIDSPRAY="ACID", CROSSPOISON="POISON_STING", GUNKSHOT="SLUDGE",
  POISONJAB="POISON_STING", COIL="TOXIC", VENOMDRENCH="POISON_GAS",

  -- Ground
  SANDATTACK="SAND_ATTACK", MUDSLAP="SAND_ATTACK", EARTHQUAKE="EARTHQUAKE",
  EARTHPOWER="EARTHQUAKE", BULLDOZE="EARTHQUAKE", DIG="DIG", FISSURE="FISSURE",
  BONEMERANG="BONE_CLUB", BONECLUB="BONE_CLUB", DRILLRUN="DIG",
  HIGHHORSEPOWER="EARTHQUAKE", SANDTOMB="SAND_ATTACK",
  PRECIPICEBLADES="EARTHQUAKE", THOUSANDWAVES="EARTHQUAKE",

  -- Rock
  ROCKTHROW="ROCK_THROW", ROCKSLIDE="ROCK_SLIDE", ROCKBLAST="ROCK_THROW",
  SMACKDOWN="ROCK_THROW", STONEEDGE="ROCK_SLIDE", POWERGEM="ROCK_THROW",
  ROCKTOMB="ROCK_THROW", ANCIENTPOWER="ROCK_SLIDE", HEADSMASH="ROCK_SLIDE",
  DIAMONDSTORM="ROCK_SLIDE",

  -- Bug
  STRINGSHOT="STRING_SHOT", TWINEEDLE="TWINEEDLE", PINMISSILE="PIN_MISSILE",
  FURYATTACK="FURY_ATTACK", LEECHLIFE="LEECH_LIFE", BUGBITE="LEECH_LIFE",
  XSCISSOR="SLASH", UTURN="GUST", SIGNALBEAM="STRING_SHOT",
  SILVERWIND="GUST", STRUGGLEBUG="STRING_SHOT", RAGEPOWDER="STRING_SHOT",

  -- Flying
  GUST="GUST", WINGATTACK="WING_ATTACK", PECK="PECK", DRILLPECK="DRILL_PECK",
  FLY="FLY", SKYATTACK="SKY_ATTACK", AERIALACE="GUST", AIRSLASH="GUST",
  AIRCUTTER="GUST", HURRICANE="GUST", ACROBATICS="FLY", BRAVEBIRD="WING_ATTACK",
  PLUCK="PECK", ROOST="FLY", FEATHERDANCE="GUST", DEFOG="GUST",

  -- Fighting
  KARATECHOP="KARATE_CHOP", LOWKICK="LOW_KICK", DOUBLEKICK="DOUBLE_KICK",
  TRIPLEKICK="DOUBLE_KICK", JUMPKICK="JUMP_KICK", HIGHJUMPKICK="JUMP_KICK",
  ROLLINGKICK="ROLLING_KICK", SUBMISSION="SUBMISSION", COUNTER="COUNTER",
  SEISMICTOSS="SEISMIC_TOSS", BRICKBREAK="ROLLING_KICK",
  CLOSECOMBAT="SUBMISSION", AURASPHERE="MEGA_PUNCH", FORCEPALM="THUNDER_WAVE",
  VACUUMWAVE="GUST", SUPERPOWER="SUBMISSION", LOWSWEEP="LOW_KICK",
  CIRCLETHROW="SEISMIC_TOSS", VITALTHROW="SUBMISSION", REVENGE="COUNTER",
  ARMTHRUST="DOUBLE_KICK", STORMTHROW="MEGA_PUNCH", SACREDSWORD="SLASH",

  -- Psychic
  CONFUSION="CONFUSION", PSYBEAM="PSYBEAM", PSYCHIC="PSYCHIC",
  PSYWAVE="PSYWAVE", HYPNOSIS="HYPNOSIS", DREAMEATER="DREAM_EATER",
  EXTRASENSORY="PSYBEAM", PSYSHOCK="PSYCHIC", PSYSTRIKE="PSYCHIC",
  PSYCHOCUT="SLASH", ZENHEADBUTT="HEADBUTT", FUTURESIGHT="PSYCHIC",
  STOREDPOWER="PSYCHIC", EXPANDINGFORCE="PSYCHIC",
  SYNCHRONOISE="PSYCHIC", TELEKINESIS="CONFUSION", GRAVITY="CONFUSION",
  PSYCHUP="MIMIC",

  -- Ghost
  LICK="LICK", NIGHTSHADE="NIGHT_SHADE", CONFUSERAY="CONFUSE_RAY",
  SHADOWBALL="NIGHT_SHADE", SHADOWCLAW="SLASH", SHADOWSNEAK="LICK",
  SHADOWPUNCH="MEGA_PUNCH", HEX="NIGHT_SHADE", POLTERGEIST="NIGHT_SHADE",
  PHANTOMFORCE="NIGHT_SHADE", DESTINYBOND="CONFUSE_RAY",

  -- Dragon
  DRAGONRAGE="DRAGON_RAGE", DRAGONCLAW="SLASH", DRAGONBREATH="DRAGON_RAGE",
  DRAGONPULSE="DRAGON_RAGE", OUTRAGE="DRAGON_RAGE", DRACOMETEOR="DRAGON_RAGE",
  DRAGONTAIL="DRAGON_RAGE", COREENFORCER="DRAGON_RAGE",

  -- Dark
  FEINTATTACK="LICK", PURSUIT="LICK", SUCKERPUNCH="MEGA_PUNCH",
  THIEF="LICK", KNOCKOFF="LICK", FOULPLAY="LICK", DARKPULSE="NIGHT_SHADE",
  SNARL="ROAR", DARKVOID="HYPNOSIS", PAYBACK="LICK",
  NIGHTDAZE="NIGHT_SHADE", DARKESTLARIAT="TACKLE", THROATCHOP="BITE",

  -- Steel
  METALCLAW="SLASH", METALBURST="COUNTER", IRONHEAD="HEADBUTT",
  IRONTAIL="SLASH", IRONDEFENSE="HARDEN", FLASHCANNON="HYPER_BEAM",
  GYROBALL="TACKLE", HEAVYSLAM="TACKLE", SMARTSTRIKE="SLASH",
  STEELBEAM="HYPER_BEAM", DOOMDESIRE="HYPER_BEAM",

  -- Fairy
  FAIRYWIND="GUST", DISARMINGVOICE="HYPER_BEAM", DAZZLINGGLEAM="HYPER_BEAM",
  MOONBLAST="HYPER_BEAM", PLAYROUGH="TACKLE", MISTYEXPLOSION="EXPLOSION",
  AROMATICMIST="MIST", FAIRYLOCK="BARRIER", CRAFTYSHIELD="BARRIER",
  MOONLIGHT="RECOVER", BABYDOLLEYES="GROWL", CHARM="GROWL", SWEETKISS="SING"
}

local ELEMENTAL_NAME_ANIMS = {
  FIRE = "EMBER",
  FLAME = "EMBER",
  WATER = "WATER_GUN",
  AQUA = "WATER_GUN",
  ELECTRIC = "THUNDER_SHOCK",
  THUNDER = "THUNDER_SHOCK",
  GRASS = "RAZOR_LEAF",
  LEAF = "RAZOR_LEAF",
  ICE = "ICE_BEAM",
  FROST = "ICE_BEAM",
  POISON = "POISON_STING",
  ACID = "ACID",
  GROUND = "SAND_ATTACK",
  EARTH = "EARTHQUAKE",
  ROCK = "ROCK_THROW",
  STONE = "ROCK_THROW",
  BUG = "STRING_SHOT",
  FLYING = "GUST",
  AIR = "GUST",
  PSYCHIC = "CONFUSION",
  PSY = "CONFUSION",
  GHOST = "LICK",
  SHADOW = "NIGHT_SHADE",
  DRAGON = "DRAGON_RAGE",
  DARK = "LICK",
  STEEL = "ROCK_THROW",
  FAIRY = "CONFUSION"
}

local STATUS_ANIMS = {
  -- Gen 1 has a dedicated non-attack Ice/field animation: MIST.
  -- Use it for non-damaging Ice effects instead of reusing ICE_BEAM.
  AURORAVEIL = "MIST",
  HAIL = "MIST",
  HAZE = "MIST",
  MIST = "MIST",
  CHILLYRECEPTION = "MIST",
  BURN = "EMBER",
  FREEZE = "ICE_BEAM",
  PARALYZE = "THUNDER_WAVE",
  POISON = "POISON_STING",
  SLEEP = "HYPNOSIS",
  CONFUSION = "CONFUSE_RAY"
}

local function statusAnimation(move)
  local effect = tostring(move and move.effect or ""):upper()
  if effect == "BURN_SIDE_EFFECT1" or effect == "BURN_SIDE_EFFECT2" then
    return STATUS_ANIMS.BURN
  end
  if effect == "FREEZE_SIDE_EFFECT1" then
    return STATUS_ANIMS.FREEZE
  end
  if effect == "PARALYZE_EFFECT" or effect == "PARALYZE_SIDE_EFFECT1"
      or effect == "PARALYZE_SIDE_EFFECT2" then
    return STATUS_ANIMS.PARALYZE
  end
  if effect == "POISON_EFFECT" or effect == "POISON_SIDE_EFFECT1"
      or effect == "POISON_SIDE_EFFECT2" then
    return STATUS_ANIMS.POISON
  end
  if effect == "SLEEP_EFFECT" then
    return STATUS_ANIMS.SLEEP
  end
  if effect == "CONFUSION_EFFECT" or effect == "CONFUSION_SIDE_EFFECT" then
    return STATUS_ANIMS.CONFUSION
  end
  return nil
end

local function animationForMove(move)
  if not move then return nil end

  local name = tostring(move.name or move.id or ""):upper():gsub("[^A-Z]", "")
  local isDamaging = (tonumber(move.power) or 0) > 0

  -- A non-damaging move should never receive a physical/special attack
  -- animation merely because its type is elemental. Status-inflicting moves
  -- are the exception: use the visual associated with the status itself.
  local nonDamagingAnim = STATUS_ANIMS[move.id]
  if not isDamaging then
    if nonDamagingAnim then return nonDamagingAnim end
    return statusAnimation(move)
  end

  -- For damaging moves, an explicit elemental word in the name takes
  -- priority over the mechanical/visual family. For example, Ice Beam and
  -- Fire Punch must use the Ice and Fire palettes even though "Beam" and
  -- "Punch" have their own animation families.
  local elementalWords = {
    "FIRE","FLAME","WATER","AQUA","ELECTRIC","THUNDER","GRASS","LEAF",
    "ICE","FROST","POISON","ACID","GROUND","EARTH","ROCK","STONE","BUG",
    "FLYING","AIR","PSYCHIC","PSY","GHOST","SHADOW","DRAGON","DARK",
    "STEEL","FAIRY"
  }
  for _, word in ipairs(elementalWords) do
    if name:find(word, 1, true) then
      return ELEMENTAL_NAME_ANIMS[word]
    end
  end

  if move.id and MOVE_ANIMS[move.id] then return MOVE_ANIMS[move.id] end

  -- Semantic fallback for future National Dex additions.
  if name:find("SLASH") or name:find("SCISSOR") then return "SLASH" end
  if name:find("PUNCH") then return "MEGA_PUNCH" end
  if name:find("KICK") then return "MEGA_KICK" end
  if name:find("BITE") or name:find("FANG") then return "BITE" end
  if name:find("BEAM") or name:find("BLAST") then return "HYPER_BEAM" end
  if name:find("TACKLE") or name:find("SLAM") then return "TACKLE" end
  return TYPE_ANIMS[move.type]
end

local function hasNativeAnimation(battle, moveId)
  local data = battle and battle.data
  local anims = data and data.moveAnims
  return type(anims) == "table" and anims[moveId] ~= nil
end

return function(mod)
  if not mod.find("battle_effect_colors") then
    mod.log:error("Battle Effect Colors - National Dex Support requires battle_effect_colors")
    return
  end
  if not mod.find("national_dex") then
    mod.log:error("Battle Effect Colors - National Dex Support requires national_dex")
    return
  end

  if BattleState.nationalDexBattleEffectAnimationsInstalled then return end

  local original = BattleState.performMove

  function BattleState:performMove(user, target, moveInst, isCalled)
    local move = moveInst and self:moveDef(moveInst)
    local moveId = move and move.id
    local moveType = move and move.type

    original(self, user, target, moveInst, isCalled)

    -- Never replace an animation that the base game already supplies.
    -- This makes the companion additive: National Dex moves get a fallback,
    -- while the original 165 Gen 1 moves retain their authentic animations.
    if not moveId or not moveType or hasNativeAnimation(self, moveId) then
      return
    end

    local fallback = animationForMove(move)
    local row = self.moveAnimRow

    -- Charge/failure paths may intentionally cancel the normal move animation.
    -- Only redirect the ordinary queued move row when it is still present.
    if fallback and row and row.anim == moveId then
      row.anim = fallback
    end
  end

  BattleState.nationalDexBattleEffectAnimationsInstalled = true
  mod.log:info("National Dex battle animation fallbacks installed")
end
